version: '3'
services:

    app:
        build: ./docker/app
        container_name: laravel-app
        volumes:
            - ./:/var/www/project
            - ./docker/apache/apache.conf:/etc/httpd/conf/httpd.conf
        ports:
            - 3322:80
        tty: true
        working_dir: /var/www/project

        links:
            - db
            - redis
    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - 33000:3306
        volumes:
            - mysql:/var/lib/mysql
    redis:
        image: redis
        container_name: redis
        ports:
            - 33001:6379
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        # redisの永続化
        # コンフィグを書き換えた状態でredisを起動する
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes

volumes:
    mysql:
